#!/usr/bin/env python3

#count AT content
seq1 = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCG'

#make tester seq
test_seq1 = seq1[0:10]
test_len = len(test_seq1)
test_Acount = test_seq1.count('A')
test_Tcount = test_seq1.count('T')
test_ATcount = test_Acount + test_Tcount

#below doesn't work, neither 'and', 'or' or ','
#test_ATcount = test_seq1.count('A','T')

print(f"for {test_seq1}, 'A' count is {test_Acount}, 'T' count is {test_Tcount}, 'AT' count is {test_Acount + test_Tcount}")

print(f'test AT count is {test_ATcount}')

#GC count
test_GCcount = test_len - test_ATcount
print(f"{test_seq1} has 'AT' count of {test_ATcount} and 'GC' count of {test_GCcount}")

#real AT count
seq1_len = len(seq1)
seq1_Acount = seq1.count('A')
seq1_Tcount = seq1.count('T')
seq1_ATcount = seq1_Acount + seq1_Tcount
seq1_GCcount = seq1_len - seq1_ATcount

#print
print(f"for {seq1} with length of {seq1_len}, 'AT' content is {seq1_ATcount} and 'GC' content is {seq1_GCcount}, proportion of AT:GC is {seq1_ATcount/seq1_len}")




